# typings/hid/__init__.pyi
from typing import Optional, Literal, TypedDict

class _hid_device_info(TypedDict):
    path: bytes  # char -> bytes
    vendor_id: int  # unsigned short
    product_id: int  # unsigned short
    serial_number: str  # wchar_t* -> str
    release_number: int  # unsigned short
    manufacturer_string: str  # wchar_t* -> str
    product_string: str  # wchar_t* -> str
    usage_page: int  # unsigned short
    usage: int  # unsigned short
    interface_number: int  # int

class device:
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def error(self) -> str: ...
    def get_feature_report(self, report_num: int, max_length: int) -> list[int]: ...
    def get_indexed_string(self, index: int) -> str: ...
    def get_input_report(self, report_num: int, max_length: int) -> list[int]: ...
    def get_manufacturer_string(self) -> str: ...
    def get_product_string(self) -> str: ...
    def get_serial_number_string(self) -> str: ...
    def open(
        self,
        vendor_id: int = 0,
        product_id: int = 0,
        serial_number: Optional[str] = None,
    ) -> None: ...
    def open_path(self, device_path: bytes) -> None: ...
    def read(self, max_length: int, timeout_ms: int = 0) -> list[int]: ...
    def send_feature_report(self, data: bytes | list[int]) -> int: ...
    def set_nonblocking(self, nonblock: Literal[1, 0, True, False]) -> int: ...
    def write(self, data: bytes | list[int]) -> int: ...

def enumerate(vendor_id: int = 0, product_id: int = 0) -> list[_hid_device_info]: ...

__all__ = ["device", "enumerate"]
